[mgr]
show_hidden    = true
sort_dir_first = true
linemode = "size_and_permissions"

[opener]
edit = [
  { run = "vim \"$@\"", block = true }
]
[open]
prepend_rules = [
  { mime = "text/*", use = "edit"},
]
